version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: loan_app_db
    environment:
      POSTGRES_DB: loan_app
      POSTGRES_USER: loan_user
      POSTGRES_PASSWORD: loan_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loan_user -d loan_app"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: loan_app_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: